### PR TITLE
Adds two new option parameters.

### PR DESCRIPTION
**Pull request by robertomlsoares**
Hey there. I'm internationalizing the app that I'm making that uses this library and I'd like to be able to change the titles of the download and remove buttons. So I made these changes.
The first option added is called saveTitle and it defines the title of the button that downloads the tiles.
The second one is called rmTitle and it defines the title of the button that removes the tiles.
I also updated the README with the new options.
What do you think?

### CODE REVIEW

**Comment by allartk** [comment]
I am not sure if a extra parameter is the way to go. Will it solve your issue if the hard coded title attribute is removed? You may add your own logic (eg a titile attribute) to the html of saveText and rmText?

**Comment by robertomlsoares** [comment]
No, there is no problem with the hard coded attribute. As you said, I could've just used jquery to change the title I guess, but that is not so elegant imo. I thought of using parameters to make it more clean and maybe others would face the same problem as me, so it would be fixed for them too. But feel free to reject the pull request, I can just make my own build with the changes.

**Comment by allartk** [comment]
Thanks for the feedback. Since i want to try to limit the number of options a bit, an offer flexibility i took different approach: https://github.com/allartk/leaflet.offline/commit/e4eefac03e07754b7ba4724a9bf78b9ed0f92c4b Let me know if this fixes your issue to (or keep it in your branch)

**Comment by robertomlsoares** [comment]
Ah yeah, that's a good idea, I will try it out tomorrow but it should work. Thanks a lot! :)

**Pull request closed without merging**
